#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Create employee profiles file table"""
import sqlalchemy_utils

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '232d55dac463'
down_revision = 'aa257b0369b5'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_profiles_file_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_employee_profiles_file_metadata_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['employee_profiles.id'], name=op.f('fk_employee_profiles_file_metadata_record_id_employee_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_profiles_file_metadata'))
    )
    op.create_index(op.f('ix_employee_profiles_file_metadata_object_version_id'), 'employee_profiles_file_metadata', ['object_version_id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_file_metadata_record_id'), 'employee_profiles_file_metadata', ['record_id'], unique=False)
    op.create_index('uidx_employee_profiles_file_metadata_record_id_key', 'employee_profiles_file_metadata', ['record_id', 'key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uidx_employee_profiles_file_metadata_record_id_key', table_name='employee_profiles_file_metadata')
    op.drop_index(op.f('ix_employee_profiles_file_metadata_record_id'), table_name='employee_profiles_file_metadata')
    op.drop_index(op.f('ix_employee_profiles_file_metadata_object_version_id'), table_name='employee_profiles_file_metadata')
    op.drop_table('employee_profiles_file_metadata')
    # ### end Alembic commands ###
