#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add bucket columns to employee profile record."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babfb2352efd'
down_revision = '232d55dac463'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.add_column('employee_profiles', sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_index(op.f('ix_employee_profiles_bucket_id'), 'employee_profiles', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_media_bucket_id'), 'employee_profiles', ['media_bucket_id'], unique=False)
    op.create_foreign_key(op.f('fk_employee_profiles_media_bucket_id_files_bucket'), 'employee_profiles', 'files_bucket', ['media_bucket_id'], ['id'])
    op.create_foreign_key(op.f('fk_employee_profiles_bucket_id_files_bucket'), 'employee_profiles', 'files_bucket', ['bucket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_employee_profiles_bucket_id_files_bucket'), 'employee_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_employee_profiles_media_bucket_id_files_bucket'), 'employee_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_employee_profiles_media_bucket_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_bucket_id'), table_name='employee_profiles')
    op.drop_column('employee_profiles', 'media_bucket_id')
    op.drop_column('employee_profiles', 'bucket_id')
    # ### end Alembic commands ###
